server:
  port: 9296
spring:
  application:
    name: CLOUD-CONFIG
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/adil-mo/config-server
